import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./utils/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#FEF2F3",
          100: "#FDE3E5",
          200: "#FBCBD0",
          300: "#F8A3AB",
          400: "#F2707C",
          500: "#E83D4D",
          600: "#E11D2E",
          700: "#BE1528",
          800: "#9D1626",
          900: "#821822",
          950: "#480A12",
          DEFAULT: "#E11D2E",
          foreground: "#FFFFFF",
        },
        primary: {
          DEFAULT: "#E11D2E",
          dark: "#BE1528",
          light: "#E83D4D",
          foreground: "#FFFFFF",
        },
        background: "#F8FAFC",
        surface: {
          DEFAULT: "#FFFFFF",
          hover: "#F8FAFC",
          active: "#F1F5F9",
          "2": "#F1F5F9",
        },
        fg: {
          primary: "#0F172A",
          secondary: "#475569",
          tertiary: "#64748B",
        },
        foreground: {
          DEFAULT: "#0F172A",
          secondary: "#475569",
          muted: "#64748B",
        },
        border: {
          DEFAULT: "#E2E8F0",
          default: "#E2E8F0",
          strong: "#CBD5E1",
        },
        success: {
          DEFAULT: "#10B981",
          50: "#ECFDF5",
          100: "#D1FAE5",
          foreground: "#065F46",
        },
        warning: {
          DEFAULT: "#F59E0B",
          50: "#FFFBEB",
          100: "#FEF3C7",
          foreground: "#92400E",
        },
        info: {
          DEFAULT: "#3B82F6",
          50: "#EFF6FF",
          100: "#DBEAFE",
          foreground: "#1E40AF",
        },
        accent: {
          blue: "#3B82F6",
        },
        wg: {
          primary: "var(--wg-primary)",
          "primary-dark": "var(--wg-primary-dark)",
          "primary-light": "var(--wg-primary-light)",
          background: "var(--wg-bg)",
          surface: "var(--wg-surface)",
          "surface-2": "var(--wg-bg-secondary)",
          heading: "var(--wg-text-primary)",
          body: "var(--wg-text-secondary)",
          muted: "var(--wg-text-muted)",
          border: "var(--wg-border)",
          success: "var(--wg-success)",
          warning: "var(--wg-warning)",
          info: "var(--wg-info)",
          "accent-blue": "var(--wg-info)",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        heading: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains)", "ui-monospace", "SFMono-Regular", "monospace"],
        numeric: ["var(--font-jetbrains)", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1.4", letterSpacing: "-0.011em" }],
        sm: ["0.8125rem", { lineHeight: "1.45", letterSpacing: "-0.011em" }],
        base: ["0.875rem", { lineHeight: "1.45", letterSpacing: "-0.011em" }],
        md: ["0.9375rem", { lineHeight: "1.45", letterSpacing: "-0.011em" }],
        lg: ["1.0625rem", { lineHeight: "1.4", letterSpacing: "-0.018em" }],
        xl: ["1.25rem", { lineHeight: "1.25", letterSpacing: "-0.022em" }],
        "2xl": ["1.5rem", { lineHeight: "1.2", letterSpacing: "-0.024em" }],
        "3xl": ["1.875rem", { lineHeight: "1.15", letterSpacing: "-0.028em" }],
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      letterSpacing: {
        body: "-0.011em",
        heading: "-0.022em",
      },
      lineHeight: {
        body: "1.45",
        heading: "1.25",
      },
      spacing: {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "6": "24px",
        "8": "32px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
        "32": "128px",
      },
      maxWidth: {
        landing: "1200px",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "4xl": "2rem",
      },
      boxShadow: {
        xs: "var(--wg-shadow-xs)",
        sm: "var(--wg-shadow-sm)",
        DEFAULT: "var(--wg-shadow)",
        md: "var(--wg-shadow-md)",
        lg: "var(--wg-shadow-lg)",
        brand: "var(--wg-shadow-brand)",
      },
      animation: {
        "fade-up": "fade-up 0.6s ease-out both",
        "pulse-soft": "pulse-soft 2.5s ease-in-out infinite",
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.6", transform: "scale(0.92)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
