/**
 * Semantic color tokens — mirrors app/colors.css
 * @see docs/COLOR_TOKENS.md
 */

/** CSS custom property names */
export const colorVars = {
  // Surfaces
  surfacePage: "--surface-page",
  surfacePrimary: "--surface-primary",
  surfaceSecondary: "--surface-secondary",
  surfaceElevated: "--surface-elevated",
  surfaceOverlay: "--surface-overlay",
  surfaceInverse: "--surface-inverse",
  surfaceDisabled: "--surface-disabled",
  // Text
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textTertiary: "--text-tertiary",
  textInverse: "--text-inverse",
  textDisabled: "--text-disabled",
  textOnAccent: "--text-on-accent",
  // Borders
  borderDefault: "--border-default",
  borderMuted: "--border-muted",
  borderStrong: "--border-strong",
  borderFocus: "--border-focus",
  // Brand / accent
  accent: "--accent",
  accentHover: "--accent-hover",
  accentPressed: "--accent-pressed",
  accentSelected: "--accent-selected",
  accentDisabled: "--accent-disabled",
  accentSubtle: "--accent-subtle",
  accentMuted: "--accent-muted",
  accentForeground: "--accent-foreground",
  // Success
  success: "--success",
  successHover: "--success-hover",
  successPressed: "--success-pressed",
  successSelected: "--success-selected",
  successDisabled: "--success-disabled",
  successSubtle: "--success-subtle",
  successForeground: "--success-foreground",
  successBorder: "--success-border",
  // Warning
  warning: "--warning",
  warningHover: "--warning-hover",
  warningPressed: "--warning-pressed",
  warningSelected: "--warning-selected",
  warningDisabled: "--warning-disabled",
  warningSubtle: "--warning-subtle",
  warningForeground: "--warning-foreground",
  warningBorder: "--warning-border",
  // Error / danger
  danger: "--danger",
  dangerHover: "--danger-hover",
  dangerPressed: "--danger-pressed",
  dangerSelected: "--danger-selected",
  dangerDisabled: "--danger-disabled",
  dangerSubtle: "--danger-subtle",
  dangerForeground: "--danger-foreground",
  dangerBorder: "--danger-border",
  error: "--error",
  errorHover: "--error-hover",
  errorPressed: "--error-pressed",
  errorSelected: "--error-selected",
  errorDisabled: "--error-disabled",
  errorSubtle: "--error-subtle",
  errorForeground: "--error-foreground",
  errorBorder: "--error-border",
  // Information
  info: "--info",
  infoHover: "--info-hover",
  infoPressed: "--info-pressed",
  infoSelected: "--info-selected",
  infoDisabled: "--info-disabled",
  infoSubtle: "--info-subtle",
  infoForeground: "--info-foreground",
  infoBorder: "--info-border",
  // Interactive
  interactiveHover: "--interactive-hover",
  interactivePressed: "--interactive-pressed",
  interactiveSelected: "--interactive-selected",
  interactiveDisabled: "--interactive-disabled",
  interactiveHoverForeground: "--interactive-hover-foreground",
  // Focus
  focusRingColor: "--focus-ring-color",
  focusRingOffsetColor: "--focus-ring-offset-color",
  focusRingWidth: "--focus-ring-width",
  focusRingOffset: "--focus-ring-offset",
  focusRing: "--focus-ring",
  // Charts
  chart1: "--chart-1",
  chart2: "--chart-2",
  chart3: "--chart-3",
  chart4: "--chart-4",
  chart5: "--chart-5",
} as const;

/** Static light-theme values for emails, charts, and server contexts */
export const colors = {
  light: {
    surfacePage: "#f7f8fa",
    surfacePrimary: "#ffffff",
    surfaceSecondary: "#eef0f3",
    surfaceElevated: "#ffffff",
    textPrimary: "#111318",
    textSecondary: "#4b5563",
    textTertiary: "#8b939e",
    textDisabled: "#b8bfc8",
    borderDefault: "#e2e5eb",
    borderMuted: "#eef0f3",
    borderStrong: "#c8cdd6",
    accent: "#b91c1c",
    accentHover: "#9a1818",
    accentPressed: "#7f1414",
    success: "#146b4a",
    successHover: "#105a3e",
    warning: "#8a5c00",
    warningHover: "#704b00",
    danger: "#b42318",
    dangerHover: "#912018",
    info: "#2b5f8a",
    infoHover: "#234d71",
    interactiveHover: "#eef0f3",
    interactivePressed: "#e2e5eb",
    focusRing: "#b91c1c",
  },
  dark: {
    surfacePage: "#0c0e12",
    surfacePrimary: "#14171d",
    surfaceSecondary: "#1c2028",
    surfaceElevated: "#181c24",
    textPrimary: "#f0f2f5",
    textSecondary: "#9ca3af",
    textTertiary: "#6b7280",
    textDisabled: "#4b5563",
    borderDefault: "rgba(255, 255, 255, 0.08)",
    borderMuted: "rgba(255, 255, 255, 0.05)",
    borderStrong: "rgba(255, 255, 255, 0.14)",
    accent: "#d43d52",
    accentHover: "#e85468",
    accentPressed: "#c42d42",
    success: "#3d9b74",
    successHover: "#4db088",
    warning: "#c9a227",
    warningHover: "#dbb43a",
    danger: "#e05243",
    dangerHover: "#ec6a5d",
    info: "#5a8fc4",
    infoHover: "#6da3d6",
    interactiveHover: "#1c2028",
    interactivePressed: "#252a34",
    focusRing: "#d43d52",
  },
} as const;

/** Semantic color groups with interactive states */
export const semanticColors = {
  brand: ["accent", "accentHover", "accentPressed", "accentSelected", "accentDisabled", "accentSubtle", "accentMuted", "accentForeground"],
  success: ["success", "successHover", "successPressed", "successSelected", "successDisabled", "successSubtle", "successForeground", "successBorder"],
  warning: ["warning", "warningHover", "warningPressed", "warningSelected", "warningDisabled", "warningSubtle", "warningForeground", "warningBorder"],
  error: ["error", "errorHover", "errorPressed", "errorSelected", "errorDisabled", "errorSubtle", "errorForeground", "errorBorder"],
  info: ["info", "infoHover", "infoPressed", "infoSelected", "infoDisabled", "infoSubtle", "infoForeground", "infoBorder"],
  interactive: ["interactiveHover", "interactivePressed", "interactiveSelected", "interactiveDisabled", "interactiveHoverForeground"],
  focus: ["focusRingColor", "focusRingOffsetColor", "focusRingWidth", "focusRingOffset", "focusRing"],
} as const;
