/** Semantic color tokens — mirrors app/tokens.css */

export const colors = {
  light: {
    surfacePage: "#fafafa",
    surfacePrimary: "#ffffff",
    surfaceSecondary: "#f4f4f5",
    surfaceElevated: "#ffffff",
    textPrimary: "#18181b",
    textSecondary: "#52525b",
    textTertiary: "#a1a1aa",
    textInverse: "#fafafa",
    borderDefault: "#e4e4e7",
    borderMuted: "#f4f4f5",
    borderStrong: "#d4d4d8",
    accent: "#b91c1c",
    accentHover: "#991b1b",
    danger: "#dc2626",
    warning: "#d97706",
    success: "#059669",
    info: "#2563eb",
  },
  dark: {
    surfacePage: "#09090b",
    surfacePrimary: "#18181b",
    surfaceSecondary: "#27272a",
    surfaceElevated: "#18181b",
    textPrimary: "#fafafa",
    textSecondary: "#a1a1aa",
    textTertiary: "#71717a",
    textInverse: "#18181b",
    borderDefault: "rgba(255, 255, 255, 0.08)",
    borderMuted: "rgba(255, 255, 255, 0.05)",
    borderStrong: "rgba(255, 255, 255, 0.14)",
    accent: "var(--danger)",
    accentHover: "#dc2626",
    danger: "#f87171",
    warning: "#fbbf24",
    success: "#34d399",
    info: "#60a5fa",
  },
} as const;

/** CSS custom property names for programmatic access */
export const colorVars = {
  surfacePage: "--surface-page",
  surfacePrimary: "--surface-primary",
  surfaceSecondary: "--surface-secondary",
  surfaceElevated: "--surface-elevated",
  textPrimary: "--text-primary",
  textSecondary: "--text-secondary",
  textTertiary: "--text-tertiary",
  textInverse: "--text-inverse",
  borderDefault: "--border-default",
  borderMuted: "--border-muted",
  borderStrong: "--border-strong",
  accent: "--accent",
  accentHover: "--accent-hover",
  accentSubtle: "--accent-subtle",
  danger: "--danger",
  dangerSubtle: "--danger-subtle",
  warning: "--warning",
  warningSubtle: "--warning-subtle",
  success: "--success",
  successSubtle: "--success-subtle",
  info: "--info",
  infoSubtle: "--info-subtle",
} as const;
